################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Drivers/BSP/Components/adv7533 \
Drivers/BSP/Components/dp83848 \
Drivers/BSP/Components/exc7200 \
Drivers/BSP/Components/ft3x67 \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/Components/ft6x06 \
Drivers/BSP/Components/lan8742 \
Drivers/BSP/Components/mfxstm32l152 \
Drivers/BSP/Components/nt35510 \
Drivers/BSP/Components/otm8009a \
Drivers/BSP/Components/ov5640 \
Drivers/BSP/Components/ov9655 \
Drivers/BSP/Components/s5k5cag \
Drivers/BSP/Components/st7735 \
Drivers/BSP/Components/st7789h2 \
Drivers/BSP/Components/stmpe811 \
Drivers/BSP/Components/ts3510 \
Drivers/BSP/Components/wm8994 \
Drivers/BSP/STM32746G-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Src \
Startup \
hal_stm_lvgl/tft \
hal_stm_lvgl/touchpad \
lvgl/env_support/pikascript \
lvgl/env_support/rt-thread \
lvgl/env_support/rt-thread/squareline \
lvgl/src/core \
lvgl/src/debugging/monkey \
lvgl/src/debugging/sysmon \
lvgl/src/debugging/test \
lvgl/src/debugging/vg_lite_tvg \
lvgl/src/display \
lvgl/src/draw/convert/helium \
lvgl/src/draw/convert \
lvgl/src/draw/convert/neon \
lvgl/src/draw/dma2d \
lvgl/src/draw/espressif/ppa \
lvgl/src/draw/eve \
lvgl/src/draw \
lvgl/src/draw/nanovg \
lvgl/src/draw/nema_gfx \
lvgl/src/draw/nxp/g2d \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/opengles \
lvgl/src/draw/renesas/dave2d \
lvgl/src/draw/sdl \
lvgl/src/draw/snapshot \
lvgl/src/draw/sw/blend/helium \
lvgl/src/draw/sw/blend \
lvgl/src/draw/sw/blend/neon \
lvgl/src/draw/sw/blend/riscv_v \
lvgl/src/draw/sw \
lvgl/src/draw/vg_lite \
lvgl/src/drivers/display/drm \
lvgl/src/drivers/display/fb \
lvgl/src/drivers/display/ft81x \
lvgl/src/drivers/display/ili9341 \
lvgl/src/drivers/display/lcd \
lvgl/src/drivers/display/nv3007 \
lvgl/src/drivers/display/nxp_elcdif \
lvgl/src/drivers/display/renesas_glcdc \
lvgl/src/drivers/display/st7735 \
lvgl/src/drivers/display/st7789 \
lvgl/src/drivers/display/st7796 \
lvgl/src/drivers/display/st_ltdc \
lvgl/src/drivers/draw/eve \
lvgl/src/drivers/evdev \
lvgl/src/drivers/libinput \
lvgl/src/drivers/nuttx \
lvgl/src/drivers/opengles/assets \
lvgl/src/drivers/opengles/glad/src \
lvgl/src/drivers/opengles \
lvgl/src/drivers/opengles/opengl_shader \
lvgl/src/drivers/qnx \
lvgl/src/drivers/sdl \
lvgl/src/drivers/uefi \
lvgl/src/drivers/wayland \
lvgl/src/drivers/windows \
lvgl/src/drivers/x11 \
lvgl/src/font/binfont_loader \
lvgl/src/font/fmt_txt \
lvgl/src/font/font_manager \
lvgl/src/font/imgfont \
lvgl/src/font \
lvgl/src/indev \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/layouts \
lvgl/src/libs/FT800-FT813 \
lvgl/src/libs/barcode \
lvgl/src/libs/bin_decoder \
lvgl/src/libs/bmp \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/frogfs/src \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif \
lvgl/src/libs/gltf/gltf_environment \
lvgl/src/libs/gltf/gltf_view/assets \
lvgl/src/libs/gltf/math \
lvgl/src/libs/gstreamer \
lvgl/src/libs/libjpeg_turbo \
lvgl/src/libs/libpng \
lvgl/src/libs/libwebp \
lvgl/src/libs/lodepng \
lvgl/src/libs/lz4 \
lvgl/src/libs/nanovg \
lvgl/src/libs/qrcode \
lvgl/src/libs/rle \
lvgl/src/libs/rlottie \
lvgl/src/libs/svg \
lvgl/src/libs/tiny_ttf \
lvgl/src/libs/tjpgd \
lvgl/src/libs/vg_lite_driver/VGLite \
lvgl/src/libs/vg_lite_driver/VGLiteKernel \
lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
lvgl/src \
lvgl/src/misc/cache/class \
lvgl/src/misc/cache/instance \
lvgl/src/misc/cache \
lvgl/src/misc \
lvgl/src/osal \
lvgl/src/others/file_explorer \
lvgl/src/others/fragment \
lvgl/src/others/translation \
lvgl/src/stdlib/builtin \
lvgl/src/stdlib/clib \
lvgl/src/stdlib \
lvgl/src/stdlib/micropython \
lvgl/src/stdlib/rtthread \
lvgl/src/stdlib/uefi \
lvgl/src/themes/default \
lvgl/src/themes \
lvgl/src/themes/mono \
lvgl/src/themes/simple \
lvgl/src/tick \
lvgl/src/widgets/3dtexture \
lvgl/src/widgets/animimage \
lvgl/src/widgets/arc \
lvgl/src/widgets/arclabel \
lvgl/src/widgets/bar \
lvgl/src/widgets/button \
lvgl/src/widgets/buttonmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/gif \
lvgl/src/widgets/image \
lvgl/src/widgets/imagebutton \
lvgl/src/widgets/ime \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/lottie \
lvgl/src/widgets/menu \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/property \
lvgl/src/widgets/roller \
lvgl/src/widgets/scale \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \

